name: get changes

on:
    workflow_call: 

jobs:
  get-changes:
    name: 📑List changes
    runs-on: ubuntu-latest
    steps:
    - name: Paths Changes Filter
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
            configuration:
                - added|modified: 'configuration/**'
            terraform:
                - 'terraform/**'
            slides:
                - 'slides.md'